default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: valley
  username: red
  password: root
  host: localhost

test:
  <<: *default
  database: valley_test
  username: red
  password: root
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
