default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: red
  password: root
  host: localhost

development:
  <<: *default
  database: valley

test:
  <<: *default
  database: valley_test

production:
  <<: *default
  database: valley_production
  username: valley
  password: <%= ENV['VALLEY_DATABASE_PASSWORD'] %>
